Iter5
a-x-a/go-metric pull request #5
Opened 2024-03-11 10:47 UTC by a-x-a

## Добавил возможность указания параметров запуска через переменные окружения

Для сервера:
- `ADDRESS` отвечает за адрес эндпоинта HTTP-сервера

Для агента:
- `ADDRESS` отвечает за адрес эндпоинта HTTP-сервера
- `REPORT_INTERVAL` позволяет переопределять `reportInterval`
- `POLL_INTERVAL` позволяет переопределять `pollInterval`

Приоритет параметров:
- Если указана переменная окружения, то используется она.
- Если нет переменной окружения, но есть аргумент командной строки (флаг), то используется он.
- Если нет ни переменной окружения, ни флага, то используется значение по умолчанию.

2024-03-11 16:39 UTC, arttet requested changes
Please add:
- https://about.codecov.io/blog/getting-started-with-code-coverage-for-golang/
- https://github.com/golangci/golangci-lint

2024-03-11 16:39 UTC, arttet commented on internal/app/server.go
> +func newServerConfig() serverConfig {
CHANGE REQUEST: it seems it should be in another package.

2024-03-11 16:39 UTC, arttet commented on internal/app/server.go
> +	err := http.ListenAndServe(s.Config.ListenAddress, r)
```suggestion
	return http.ListenAndServe(s.Config.ListenAddress, r)
```

2024-03-14 22:06 UTC, a-x-a commented
Add codecov and golangci-lint

2024-03-15 16:47 UTC, arttet approved these changes
Good job!

2024-03-15 16:47 UTC, arttet commented on internal/service/metricservice/metricservice.go
> +func (s metricService) Push(name, kind, value string) error {
```suggestion
func (s *metricService) Push(name, kind, value string) error {
```

2024-03-18 14:22 UTC, arttet approved these changes

2024-03-18 23:09 UTC, merged